<?php
/**
 * @file
 * Install file for the mobile users module.
 */

/**
 * Implements hook_schema().
 */
function std_hacks_schema() {
	$schema['mobile_users'] = array(
		'description' => 'Mobile User Information',
		'fields' => array(
			'login_id' => array(
				'description' => 'Mobile user login ID',
				'type' => 'varchar',
				'length' => 10,
				'not null' => TRUE,
			),
			'password' => array(
				'description' => 'Mobile user imei',
				'type' => 'varchar',
				'length' => 20,
				'not null' => TRUE,
			),
			'name' => array(
				'description' => 'Mobile user name',
				'type' => 'varchar',
				'length' => 50,
				'not null' => TRUE,
			),
			'access_type' => array(
				'description' => 'Mobile user access type',
				'type' => 'varchar',
				'length' => 2,
				'not null' => TRUE,
			),
			'access_code' => array(
				'description' => 'Mobile user access code',
				'type' => 'varchar',
				'length' => 3,
				'not null' => TRUE,
			),
			'approver' => array(
				'description' => 'Mobile user approver/non-approver',
				'type' => 'varchar',
				'length' => 3,
				'not null' => TRUE,
			),
			'remarks' => array(
				'description' => 'Authentication remarks',
				'type' => 'varchar',
				'length' => 10,
				'not null' => TRUE,
			),
		),
		'primary key' => array('login_id'),
	);
	return $schema;
}
function std_hacks_uninstall() {
	drupal_uninstall_schema('mobile_users');
}
?>
